#!/bin/bash

echo "Started installing Modules on Raspberry Pi SD Card"

#take time
export TIME_S=$(date +"%S")
export TIME_M=$(date +"%M")
export TIME_I=$(date +"%I")

export FAT32_DIR=~/fat32
export EXT4_DIR=~/ext4

if [ ! -d $FAT32_DIR ]
	then
		mkdir $FAT32_DIR
fi

if [ ! -d $EXT4_DIR ]
	then
		mkdir $EXT4_DIR
fi

mount /dev/sdb1/ $FAT32_DIR
mount /dev/sdb2/ $EXT4_DIR

echo "Compiling Modules:"
make ARCH=arm modules CROSS_COMPILE=/usr/bin/arm-linux-gnueabi- INSTALL_MOD_PATH=$EXT4_DIR modules

echo "Installing Modules:"
make ARCH=arm CROSS_COMPILE=/usr/bin/arm-linux-gnueabi- INSTALL_MOD_PATH=$EXT4_DIR modules_install

umount $FAT32_DIR
umount $EXT4_DIR

rmdir $FAT32_DIR
rmdir $EXT4_DIR

export TIME_S_TOTAL=$(($(date +"%S") - $TIME_S))
export TIME_M_TOTAL=$(($(date +"%M") - $TIME_M))
export TIME_I_TOTAL=$(($(date +"%I") - $TIME_I))

echo "Total Duration: " $TIME_I_TOTAL:$TIME_M_TOTAL:$TIME_I_TOTAL
